product-name: ((compliance.product_name))

product-properties:
  .properties.benchmarks:
    value: ((compliance.benchmarks))
  .properties.max_audit_log_file_size:
    value: 6 # required
  .properties.ntp_server:
    value: ((compliance.ntp_server)) # required
  .properties.scan_report_formats:
    value: ((compliance.formats))
  .properties.syslog_host:
    value: ((monitoring.syslog.host)) # required
  .properties.syslog_port:
    value: ((monitoring.syslog.port)) # required

network-properties:
  network:
    name: ((networks.services))
  other_availability_zones:
  - name: ((availability_zones.one))
  - name: ((availability_zones.two))
  - name: ((availability_zones.three))
  service_network:
    name: ((networks.services))
  singleton_availability_zone:
    name: ((availability_zones.three))
