product-name: ((p-healthwatch.product_name))

product-properties:
  .healthwatch-forwarder.boshhealth_instance_count:
    value: 1 # required
  .healthwatch-forwarder.boshtasks_instance_count:
    value: 2 # required
  .healthwatch-forwarder.canary_instance_count:
    value: 2 # required
  .healthwatch-forwarder.cli_instance_count:
    value: 2 # required
  .healthwatch-forwarder.foundation_name:
    value: pcf-((cloud))-((environment))
  .healthwatch-forwarder.health_check_az:
    value: ((p-healthwatch.forwarder.az)) # required
  .healthwatch-forwarder.health_check_vm_type:
    value: ((p-healthwatch.forwarder.vm_type)) # required
  .healthwatch-forwarder.ingestor_instance_count:
    value: 4 # required
  .healthwatch-forwarder.opsman_instance_count:
    value: 2 # required
  .healthwatch-forwarder.publish_to_eva:
    value: true # required
  .healthwatch-forwarder.worker_instance_count:
    value: 4 # required
  .mysql.skip_name_resolve:
    value: true # required
  .properties.boshtasks:
    value: enable # required
  .properties.boshtasks.enable.bosh_taskcheck_password:
    value: # required
      secret: ((p-healthwatch.bosh.password))
  .properties.boshtasks.enable.bosh_taskcheck_username:
    value: ((p-healthwatch.bosh.username))  # required
  .properties.opsman:
    value: enable # required
  .properties.opsman.enable.url:
    value: ((opsman.target)) # required
  .properties.syslog_selector:
    value: "Yes without encryption" # required
  .properties.syslog_selector.active.syslog_address:
    value: ((monitoring.syslog.host)) # required
  .properties.syslog_selector.active.syslog_port:
    value: ((monitoring.syslog.port)) # required
  .properties.syslog_selector.active.syslog_transport:
    value: tcp # required
  # .properties.syslog_selector.active_with_tls.syslog_address:
  #   value: null # required
  # .properties.syslog_selector.active_with_tls.syslog_ca_cert:
  #   value: null # required
  # .properties.syslog_selector.active_with_tls.syslog_permitted_peer:
  #   value: null # required
  # .properties.syslog_selector.active_with_tls.syslog_port:
  #   value: null # required

network-properties:
  network:
    name: ((networks.services))
  other_availability_zones:
  - name: ((availability_zones.one))
  - name: ((availability_zones.two))
  - name: ((availability_zones.three))
  service_network:
    name: ((networks.services))
  singleton_availability_zone:
    name: ((availability_zones.one))
