product-name: credhub-service-broker

product-properties:
  .properties.credhub_broker_enable_global_access_to_plans:
    value: ((credhub-service-broker.enabled)) # required

network-properties:
  network:
    name: ((networks.services))
  other_availability_zones:
  - name: ((availability_zones.one))
  - name: ((availability_zones.two))
  - name: ((availability_zones.three))
  singleton_availability_zone:
    name: ((availability_zones.one))
